name: Notify Slack

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          RELEASE_NAME=$(jq -n --arg str "${{ github.event.release.name }}" '$str')
          RELEASE_NOTES=$(jq -n --arg str "${{ github.event.release.body }}" '$str')
          PAYLOAD="{\"channel\": \"#timeline_raku\", \"username\": \"webhookbot\", \"text\": \"リリース名: $RELEASE_NAME\n\nリリースノート:\n$RELEASE_NOTES\", \"icon_emoji\": \":ghost:\"}"

          curl -X POST --data-urlencode "payload=$PAYLOAD" $SLACK_WEBHOOK_URL
