name: Release to Production

on:
  push:
    branches:
      - release

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Bump version and create tag
        run: |
          echo NEW_TAG="v$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Deploy to Vercel
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Get draft release
        run: |
          RELEASE_ID=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                    -H "Accept: application/vnd.github.v3+json" \
                    https://api.github.com/repos/${{ github.repository }}/releases \
               | jq '.[] | select(.draft==true) | .id')
          echo "RELEASE_ID=${RELEASE_ID}" >> $GITHUB_ENV
      - name: Update and publish release
        run: |
          curl -X PATCH \
             -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             -d '{"name": "${{ env.NEW_TAG }}", "tag_name": "${{ env.NEW_TAG }}", "draft": false}' \
             https://api.github.com/repos/${{ github.repository }}/releases/${{ env.RELEASE_ID }}

      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.16.0
        with:
          payload: |
            {
              "text": ":Deployed",
              "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":vercel: *<https://github.com/LeSangK/nextjs_for_le|New nextjs-for-le>* has been deployed in Vercel!"
                }
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": " https://nextjs-for-le-alesangk.vercel.app :tada:"
                  }
                ]
              }
             ]
            }
        env:
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
