name: Notify Slack of new release

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Write release body to file
        run: |
          echo "${{ github.event.release.body }}" > .github/releaseBody.txt

      - name: Format release note
        run: |
          node .github/formatReleaseNote.js

      - name: Read formatted release note
        id: format
        run: |
          cat .github/formattedReleaseBody.txt
          echo "::set-output name=body::$(<.github/formattedReleaseBody.txt)"

      - name: Send to Slack
        uses: slackapi/slack-github-action@v1.16.0
        with:
          payload: |
            {
              "text": ${{ steps.format.outputs.body }}
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
