name: Release to Production

on:
  push:
    branches:
      - release

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version here

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Configure Vercel Project
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build and Deploy to Vercel
        run: |
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Manage GitHub Release
        run: |
          # Retrieve the latest tag (previous release)
          PREVIOUS_TAG=$(git describe --tags --abbrev=0)

          # Generate new tag (current release)
          NEW_TAG="v$(date +'%Y%m%d')"

          # Create release with auto-generated release notes
          RESPONSE=$(curl -X POST \
             -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             -d "{\"tag_name\": \"$NEW_TAG\", \"name\": \"$NEW_TAG\", \"body\": \"\", \"draft\": false, \"generate_release_notes\": true}" \
             https://api.github.com/repos/${{ github.repository }}/releases)

          echo "Release created: $RESPONSE"
